version: "2.3"
services:
  kaggle:
    build:
     context: .
     shm_size: '32gb'
    shm_size: '32gb'
    container_name: kaggle
    tty: true
    volumes:
     - ./:/kaggle
     - ~/mnt/:/kaggle/mnt
    working_dir: /kaggle
    runtime: nvidia
    ports:
     - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --port 8888 --allow-root  --no-browser --LabApp.token=''